from ..base import AdyenServiceBase


class TerminalOrdersMerchantLevelApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super(TerminalOrdersMerchantLevelApi, self).__init__(client=client)
        self.service = "management"

    def list_billing_entities(self, merchantId, idempotency_key=None, **kwargs):
        """
        Get a list of billing entities
        """
        endpoint = f"/merchants/{merchantId}/billingEntities"
        endpoint = endpoint.replace('/', '', 1)
        method = "GET"
        return self.client.call_adyen_api(None, self.service, method, endpoint, idempotency_key, **kwargs)

    def list_shipping_locations(self, merchantId, idempotency_key=None, **kwargs):
        """
        Get a list of shipping locations
        """
        endpoint = f"/merchants/{merchantId}/shippingLocations"
        endpoint = endpoint.replace('/', '', 1)
        method = "GET"
        return self.client.call_adyen_api(None, self.service, method, endpoint, idempotency_key, **kwargs)

    def list_terminal_models(self, merchantId, idempotency_key=None, **kwargs):
        """
        Get a list of terminal models
        """
        endpoint = f"/merchants/{merchantId}/terminalModels"
        endpoint = endpoint.replace('/', '', 1)
        method = "GET"
        return self.client.call_adyen_api(None, self.service, method, endpoint, idempotency_key, **kwargs)

    def list_orders(self, merchantId, idempotency_key=None, **kwargs):
        """
        Get a list of orders
        """
        endpoint = f"/merchants/{merchantId}/terminalOrders"
        endpoint = endpoint.replace('/', '', 1)
        method = "GET"
        return self.client.call_adyen_api(None, self.service, method, endpoint, idempotency_key, **kwargs)

    def get_order(self, merchantId, orderId, idempotency_key=None, **kwargs):
        """
        Get an order
        """
        endpoint = f"/merchants/{merchantId}/terminalOrders/{orderId}"
        endpoint = endpoint.replace('/', '', 1)
        method = "GET"
        return self.client.call_adyen_api(None, self.service, method, endpoint, idempotency_key, **kwargs)

    def list_terminal_products(self, merchantId, idempotency_key=None, **kwargs):
        """
        Get a list of terminal products
        """
        endpoint = f"/merchants/{merchantId}/terminalProducts"
        endpoint = endpoint.replace('/', '', 1)
        method = "GET"
        return self.client.call_adyen_api(None, self.service, method, endpoint, idempotency_key, **kwargs)

    def update_order(self, request, merchantId, orderId, idempotency_key=None, **kwargs):
        """
        Update an order
        """
        endpoint = f"/merchants/{merchantId}/terminalOrders/{orderId}"
        endpoint = endpoint.replace('/', '', 1)
        method = "PATCH"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def create_shipping_location(self, request, merchantId, idempotency_key=None, **kwargs):
        """
        Create a shipping location
        """
        endpoint = f"/merchants/{merchantId}/shippingLocations"
        endpoint = endpoint.replace('/', '', 1)
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def create_order(self, request, merchantId, idempotency_key=None, **kwargs):
        """
        Create an order
        """
        endpoint = f"/merchants/{merchantId}/terminalOrders"
        endpoint = endpoint.replace('/', '', 1)
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def cancel_order(self, merchantId, orderId, idempotency_key=None, **kwargs):
        """
        Cancel an order
        """
        endpoint = f"/merchants/{merchantId}/terminalOrders/{orderId}/cancel"
        endpoint = endpoint.replace('/', '', 1)
        method = "POST"
        return self.client.call_adyen_api(None, self.service, method, endpoint, idempotency_key, **kwargs)

