from ..base import AdyenServiceBase


class TerminalSettingsTerminalLevelApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super(TerminalSettingsTerminalLevelApi, self).__init__(client=client)
        self.service = "management"

    def get_terminal_logo(self, terminalId, idempotency_key=None, **kwargs):
        """
        Get the terminal logo
        """
        endpoint = f"/terminals/{terminalId}/terminalLogos"
        method = "GET"
        return self.client.call_adyen_api(None, self.service, method, endpoint, idempotency_key, **kwargs)

    def get_terminal_settings(self, terminalId, idempotency_key=None, **kwargs):
        """
        Get terminal settings
        """
        endpoint = f"/terminals/{terminalId}/terminalSettings"
        method = "GET"
        return self.client.call_adyen_api(None, self.service, method, endpoint, idempotency_key, **kwargs)

    def update_logo(self, request, terminalId, idempotency_key=None, **kwargs):
        """
        Update the logo
        """
        endpoint = f"/terminals/{terminalId}/terminalLogos"
        method = "PATCH"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def update_terminal_settings(self, request, terminalId, idempotency_key=None, **kwargs):
        """
        Update terminal settings
        """
        endpoint = f"/terminals/{terminalId}/terminalSettings"
        method = "PATCH"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

