from .base import AdyenServiceBase


class AdyenBalanceControlServiceApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super(AdyenBalanceControlServiceApi, self).__init__(client=client)
        self.service = "balanceControlService"

    def balance_transfer(self, request, idempotency_key=None, **kwargs):
        """
        Start a balance transfer
        """
        endpoint = f"/balanceTransfer"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

