from .base import AdyenServiceBase


class AdyenBalanceControlApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super(AdyenBalanceControlApi, self).__init__(client=client)
        self.service = "balanceControl"
        self.baseUrl = "https://pal-test.adyen.com/pal/servlet/BalanceControl/v1"

    def balance_transfer(self, request, idempotency_key=None, **kwargs):
        """
        Start a balance transfer
        """
        endpoint = self.baseUrl + f"/balanceTransfer"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

