from .base import AdyenServiceBase


class AdyenDataProtectionApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super(AdyenDataProtectionApi, self).__init__(client=client)
        self.service = "dataProtection"

    def submit_subject_erasure_request(self, request, idempotency_key=None, **kwargs):
        """
        Submit a Subject Erasure Request.
        """
        endpoint = f"/requestSubjectErasure"
        endpoint = endpoint.replace('/', '', 1)
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

