"""
    Management API

    Configure and manage your Adyen company and merchant accounts, stores, and payment terminals. ## Authentication Each request to the Management API must be signed with an API key. [Generate your API key](https://docs.adyen.com/development-resources/api-credentials#generate-api-key) in the Customer Area and then set this key to the `X-API-Key` header value.  To access the live endpoints, you need to generate a new API key in your live Customer Area. ## Versioning  Management API handles versioning as part of the endpoint URL. For example, to send a request to version 1 of the `/companies/{companyId}/webhooks` endpoint, use:  ```text https://management-test.adyen.com/v1/companies/{companyId}/webhooks ```  ## Going live  To access the live endpoints, you need an API key from your live Customer Area. Use this API key to make requests to:  ```text https://management-live.adyen.com/v1 ```  # noqa: E501

    The version of the OpenAPI document: 1
    Contact: developer-experience@adyen.com
    Generated by: https://openapi-generator.tech
"""

from .base import AdyenServiceBase
from .management_dir.api_credentials_company_level_api import APICredentialsCompanyLevelApi
from .management_dir.api_credentials_merchant_level_api import APICredentialsMerchantLevelApi
from .management_dir.api_key_company_level_api import APIKeyCompanyLevelApi
from .management_dir.api_key_merchant_level_api import APIKeyMerchantLevelApi
from .management_dir.account_company_level_api import AccountCompanyLevelApi
from .management_dir.account_merchant_level_api import AccountMerchantLevelApi
from .management_dir.account_store_level_api import AccountStoreLevelApi
from .management_dir.allowed_origins_company_level_api import AllowedOriginsCompanyLevelApi
from .management_dir.allowed_origins_merchant_level_api import AllowedOriginsMerchantLevelApi
from .management_dir.client_key_company_level_api import ClientKeyCompanyLevelApi
from .management_dir.client_key_merchant_level_api import ClientKeyMerchantLevelApi
from .management_dir.my_api_credential_api import MyAPICredentialApi
from .management_dir.payment_methods_merchant_level_api import PaymentMethodsMerchantLevelApi
from .management_dir.payout_settings_merchant_level_api import PayoutSettingsMerchantLevelApi
from .management_dir.terminal_actions_company_level_api import TerminalActionsCompanyLevelApi
from .management_dir.terminal_actions_terminal_level_api import TerminalActionsTerminalLevelApi
from .management_dir.terminal_orders_company_level_api import TerminalOrdersCompanyLevelApi
from .management_dir.terminal_orders_merchant_level_api import TerminalOrdersMerchantLevelApi
from .management_dir.terminal_settings_company_level_api import TerminalSettingsCompanyLevelApi
from .management_dir.terminal_settings_merchant_level_api import TerminalSettingsMerchantLevelApi
from .management_dir.terminal_settings_store_level_api import TerminalSettingsStoreLevelApi
from .management_dir.terminal_settings_terminal_level_api import TerminalSettingsTerminalLevelApi
from .management_dir.terminals_terminal_level_api import TerminalsTerminalLevelApi
from .management_dir.users_company_level_api import UsersCompanyLevelApi
from .management_dir.users_merchant_level_api import UsersMerchantLevelApi
from .management_dir.webhooks_company_level_api import WebhooksCompanyLevelApi
from .management_dir.webhooks_merchant_level_api import WebhooksMerchantLevelApi


class AdyenManagementApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super(AdyenManagementApi, self).__init__(client=client)
        self.api_credentials_company_level_api = APICredentialsCompanyLevelApi(client=client)
        self.api_credentials_merchant_level_api = APICredentialsMerchantLevelApi(client=client)
        self.api_key_company_level_api = APIKeyCompanyLevelApi(client=client)
        self.api_key_merchant_level_api = APIKeyMerchantLevelApi(client=client)
        self.account_company_level_api = AccountCompanyLevelApi(client=client)
        self.account_merchant_level_api = AccountMerchantLevelApi(client=client)
        self.account_store_level_api = AccountStoreLevelApi(client=client)
        self.allowed_origins_company_level_api = AllowedOriginsCompanyLevelApi(client=client)
        self.allowed_origins_merchant_level_api = AllowedOriginsMerchantLevelApi(client=client)
        self.client_key_company_level_api = ClientKeyCompanyLevelApi(client=client)
        self.client_key_merchant_level_api = ClientKeyMerchantLevelApi(client=client)
        self.my_api_credential_api = MyAPICredentialApi(client=client)
        self.payment_methods_merchant_level_api = PaymentMethodsMerchantLevelApi(client=client)
        self.payout_settings_merchant_level_api = PayoutSettingsMerchantLevelApi(client=client)
        self.terminal_actions_company_level_api = TerminalActionsCompanyLevelApi(client=client)
        self.terminal_actions_terminal_level_api = TerminalActionsTerminalLevelApi(client=client)
        self.terminal_orders_company_level_api = TerminalOrdersCompanyLevelApi(client=client)
        self.terminal_orders_merchant_level_api = TerminalOrdersMerchantLevelApi(client=client)
        self.terminal_settings_company_level_api = TerminalSettingsCompanyLevelApi(client=client)
        self.terminal_settings_merchant_level_api = TerminalSettingsMerchantLevelApi(client=client)
        self.terminal_settings_store_level_api = TerminalSettingsStoreLevelApi(client=client)
        self.terminal_settings_terminal_level_api = TerminalSettingsTerminalLevelApi(client=client)
        self.terminals_terminal_level_api = TerminalsTerminalLevelApi(client=client)
        self.users_company_level_api = UsersCompanyLevelApi(client=client)
        self.users_merchant_level_api = UsersMerchantLevelApi(client=client)
        self.webhooks_company_level_api = WebhooksCompanyLevelApi(client=client)
        self.webhooks_merchant_level_api = WebhooksMerchantLevelApi(client=client)
