from .base import AdyenServiceBase


class AdyenTerminalManagementApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super(AdyenTerminalManagementApi, self).__init__(client=client)
        self.service = "terminalManagement"

    def post_assign_terminals(self, request, idempotency_key=None, **kwargs):
        """
        Assign terminals
        """
        endpoint = f"/assignTerminals"
        endpoint = endpoint.replace('/', '', 1)
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def post_find_terminal(self, request, idempotency_key=None, **kwargs):
        """
        Get the account or store of a terminal
        """
        endpoint = f"/findTerminal"
        endpoint = endpoint.replace('/', '', 1)
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def post_get_stores_under_account(self, request, idempotency_key=None, **kwargs):
        """
        Get the stores of an account
        """
        endpoint = f"/getStoresUnderAccount"
        endpoint = endpoint.replace('/', '', 1)
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def post_get_terminal_details(self, request, idempotency_key=None, **kwargs):
        """
        Get the details of a terminal
        """
        endpoint = f"/getTerminalDetails"
        endpoint = endpoint.replace('/', '', 1)
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def post_get_terminals_under_account(self, request, idempotency_key=None, **kwargs):
        """
        Get the list of terminals
        """
        endpoint = f"/getTerminalsUnderAccount"
        endpoint = endpoint.replace('/', '', 1)
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

