from ..base import AdyenServiceBase
from .general_api import GeneralApi


class AdyenPlatformsNotificationConfigurationApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super(AdyenPlatformsNotificationConfigurationApi, self).__init__(client=client)
        self.general_api = GeneralApi(client=client)
