repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 2c8dce6094fa2b4b668e74f694ca63ceffd38614
    hooks:
      - id: ruff
        name: ruff lint
        args: [--fix]
      - id: ruff-format
        name: ruff format
