sudo: true
language: python
python:
  - "2.7"
  - "3.6"
cache: pip
install:
  - python -m pip install --upgrade pycurl 
script:
  - coverage run -m unittest discover -s test -p '*Test.py'
  - pycodestyle -v
after_success:
  - coveralls
  - pylint Adyen
