sudo: true
language: python
python:
  - "2.7"
  - "3.6"
cache: pip
before_install:
  - sudo apt-get install libgnutls28-dev
install:
  - make install
script:
  - make coverage
  - pycodestyle -v
after_success:
  - coveralls
  - pylint Adyen
