sudo: true
language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install requests pycurl mock coveralls pylint pycodestyle
script:
  - coverage run -m unittest discover -s test -p '*Test.py'
  - pycodestyle -v
after_success:
  - coveralls
  - pylint Adyen
