sudo: true
language: python
python:
  - "2.6"
  - "2.7"
cache: pip
install:
  - pip install requests
  - pip install pycurl
  - pip install mock
script:
  - python -m unittest discover -s test -p '*Test.py'
