sudo: true
language: python
dist: xenial
env:
  - TESTMODE=fast
  - COVERAGE=
  - NUMPYSPEC="--pre --upgrade --timeout=60 -f $PRE_WHEELS numpy"
  - USE_SDIST=1
python:
  - "2.7"
  - "3.6"
cache: pip
install:
  - pip install requests pycurl mock coveralls pylint pycodestyle wheel
script:
  - coverage run -m unittest discover -s test -p '*Test.py'
  - pycodestyle -v
after_success:
  - coveralls
  - pylint Adyen
