[tox]
envlist = py{38,39,310,311,312,313,314}-{pycurl,requests,urllib},lint
skip_missing_interpreters=true

[testenv]
allowlist_externals = make
setenv = PYTHONHASHSEED = 34237731
deps =
    mock
    requests: requests
    pycurl: pycurl
commands =
    make tests

[testenv:lint]
allowlist_externals = make
skip_install = true
deps = ruff>=0.4.4
commands =
    ruff check Adyen test