[tox]
envlist = py{38,39,310,311,312,313,314}-{pycurl,requests,urllib},lint
skip_missing_interpreters = true
requires = tox-uv

[testenv]
allowlist_externals = make
setenv = PYTHONHASHSEED = 34237731
extras =
    test
    requests: requests
    pycurl: pycurl
commands =
    make tests

[testenv:lint]
extras = dev
commands =
    ruff check Adyen test