from ..base import AdyenServiceBase


class PosMobileApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super().__init__(client=client)
        self.service = "posMobile"
        self.baseUrl = "https://checkout-test.adyen.com/checkout/possdk/v68"

    def create_communication_session(self, request, idempotency_key=None, **kwargs):
        """
        Create a communication session

        Deprecated since POS Mobile API v68
        Use POST [/auth/certificate](https://docs.adyen.com/api-explorer/softpos-configuration-api/latest/post/auth/certificate) to establish secure communications.
        """
        endpoint = self.baseUrl + "/sessions"
        method = "POST"
        return self.client.call_adyen_api(
            request, self.service, method, endpoint, idempotency_key, **kwargs
        )
