from ..base import AdyenServiceBase
from .hosted_onboarding_page_api import HostedOnboardingPageApi
from .pci_compliance_questionnaire_page_api import PCIComplianceQuestionnairePageApi


class AdyenPlatformsHostedOnboardingPageApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super(AdyenPlatformsHostedOnboardingPageApi, self).__init__(client=client)
        self.hosted_onboarding_page_api = HostedOnboardingPageApi(client=client)
        self.pci_compliance_questionnaire_page_api = PCIComplianceQuestionnairePageApi(client=client)
