from ..base import AdyenServiceBase


class HostedOnboardingPageApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super(HostedOnboardingPageApi, self).__init__(client=client)
        self.service = "platformsHostedOnboardingPage"

    def get_onboarding_url(self, request, idempotency_key=None, **kwargs):
        """
        Get a link to a Adyen-hosted onboarding page
        """
        endpoint = f"/getOnboardingUrl"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

