from ..base import AdyenServiceBase


class PCIComplianceQuestionnairePageApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super(PCIComplianceQuestionnairePageApi, self).__init__(client=client)
        self.service = "platformsHostedOnboardingPage"

    def get_pci_questionnaire_url(self, request, idempotency_key=None, **kwargs):
        """
        Get a link to a PCI compliance questionnaire
        """
        endpoint = f"/getPciQuestionnaireUrl"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

