from ..base import AdyenServiceBase


class InitializationApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super(InitializationApi, self).__init__(client=client)
        self.service = "payouts"

    def store_payout_details(self, request, idempotency_key=None, **kwargs):
        """
        Store payout details
        """
        endpoint = f"/storeDetail"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def store_details_and_submit_payout(self, request, idempotency_key=None, **kwargs):
        """
        Store details and submit a payout
        """
        endpoint = f"/storeDetailAndSubmitThirdParty"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def submit_payout(self, request, idempotency_key=None, **kwargs):
        """
        Submit a payout
        """
        endpoint = f"/submitThirdParty"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

