from ..base import AdyenServiceBase


class InstantPayoutsApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super(InstantPayoutsApi, self).__init__(client=client)
        self.service = "payouts"

    def make_instant_card_payout(self, request, idempotency_key=None, **kwargs):
        """
        Make an instant card payout
        """
        endpoint = f"/payout"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

