from ..base import AdyenServiceBase


class BalanceAccountsApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super(BalanceAccountsApi, self).__init__(client=client)
        self.service = "balancePlatform"

    def delete_balance_accounts_balance_account_id_sweeps_sweep_id(self, balanceAccountId, sweepId, idempotency_key=None, **kwargs):
        """
        Delete a sweep
        """
        endpoint = f"/balanceAccounts/{balanceAccountId}/sweeps/{sweepId}"
        endpoint = endpoint.replace('/', '', 1)
        method = "DELETE"
        return self.client.call_adyen_api(None, self.service, method, endpoint, idempotency_key, **kwargs)

    def get_balance_accounts_balance_account_id_sweeps(self, balanceAccountId, idempotency_key=None, **kwargs):
        """
        Get all sweeps for a balance account
        """
        endpoint = f"/balanceAccounts/{balanceAccountId}/sweeps"
        endpoint = endpoint.replace('/', '', 1)
        method = "GET"
        return self.client.call_adyen_api(None, self.service, method, endpoint, idempotency_key, **kwargs)

    def get_balance_accounts_balance_account_id_sweeps_sweep_id(self, balanceAccountId, sweepId, idempotency_key=None, **kwargs):
        """
        Get a sweep
        """
        endpoint = f"/balanceAccounts/{balanceAccountId}/sweeps/{sweepId}"
        endpoint = endpoint.replace('/', '', 1)
        method = "GET"
        return self.client.call_adyen_api(None, self.service, method, endpoint, idempotency_key, **kwargs)

    def get_balance_accounts_id(self, id, idempotency_key=None, **kwargs):
        """
        Get a balance account
        """
        endpoint = f"/balanceAccounts/{id}"
        endpoint = endpoint.replace('/', '', 1)
        method = "GET"
        return self.client.call_adyen_api(None, self.service, method, endpoint, idempotency_key, **kwargs)

    def get_balance_accounts_id_payment_instruments(self, id, idempotency_key=None, **kwargs):
        """
        Get all payment instruments for a balance account
        """
        endpoint = f"/balanceAccounts/{id}/paymentInstruments"
        endpoint = endpoint.replace('/', '', 1)
        method = "GET"
        return self.client.call_adyen_api(None, self.service, method, endpoint, idempotency_key, **kwargs)

    def patch_balance_accounts_balance_account_id_sweeps_sweep_id(self, request, balanceAccountId, sweepId, idempotency_key=None, **kwargs):
        """
        Update a sweep
        """
        endpoint = f"/balanceAccounts/{balanceAccountId}/sweeps/{sweepId}"
        endpoint = endpoint.replace('/', '', 1)
        method = "PATCH"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def patch_balance_accounts_id(self, request, id, idempotency_key=None, **kwargs):
        """
        Update a balance account
        """
        endpoint = f"/balanceAccounts/{id}"
        endpoint = endpoint.replace('/', '', 1)
        method = "PATCH"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def post_balance_accounts(self, request, idempotency_key=None, **kwargs):
        """
        Create a balance account
        """
        endpoint = f"/balanceAccounts"
        endpoint = endpoint.replace('/', '', 1)
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def post_balance_accounts_balance_account_id_sweeps(self, request, balanceAccountId, idempotency_key=None, **kwargs):
        """
        Create a sweep
        """
        endpoint = f"/balanceAccounts/{balanceAccountId}/sweeps"
        endpoint = endpoint.replace('/', '', 1)
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

