from ..base import AdyenServiceBase
from .payments_app_api import PaymentsAppApi


class AdyenPaymentsAppApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super(AdyenPaymentsAppApi, self).__init__(client=client)
        self.payments_app_api = PaymentsAppApi(client=client)
