from ..base import AdyenServiceBase
from .rates_api import RatesApi


class AdyenForeignExchangeApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super().__init__(client=client)
        self.rates_api = RatesApi(client=client)
