from ..base import AdyenServiceBase


class RatesApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super().__init__(client=client)
        self.service = "foreignExchange"
        self.baseUrl = "https://balanceplatform-api-test.adyen.com/fx/api/v1"

    def calculate(self, request, idempotency_key=None, **kwargs):
        """
        Calculate amount in a different currency
        """
        endpoint = self.baseUrl + "/rates/calculate"
        method = "POST"
        return self.client.call_adyen_api(
            request, self.service, method, endpoint, idempotency_key, **kwargs
        )
