from ..base import AdyenServiceBase
from .account_holders_api import AccountHoldersApi
from .accounts_api import AccountsApi
from .verification_api import VerificationApi


class AdyenPlatformsAccountApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super(AdyenPlatformsAccountApi, self).__init__(client=client)
        self.account_holders_api = AccountHoldersApi(client=client)
        self.accounts_api = AccountsApi(client=client)
        self.verification_api = VerificationApi(client=client)
