from ..base import AdyenServiceBase


class AccountHoldersApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super(AccountHoldersApi, self).__init__(client=client)
        self.service = "platformsAccount"

    def close_account_holder(self, request, idempotency_key=None, **kwargs):
        """
        Close an account holder
        """
        endpoint = f"/closeAccountHolder"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def close_stores(self, request, idempotency_key=None, **kwargs):
        """
        Close stores
        """
        endpoint = f"/closeStores"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def create_account_holder(self, request, idempotency_key=None, **kwargs):
        """
        Create an account holder
        """
        endpoint = f"/createAccountHolder"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def get_account_holder(self, request, idempotency_key=None, **kwargs):
        """
        Get an account holder
        """
        endpoint = f"/getAccountHolder"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def get_tax_form(self, request, idempotency_key=None, **kwargs):
        """
        Get a tax form
        """
        endpoint = f"/getTaxForm"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def suspend_account_holder(self, request, idempotency_key=None, **kwargs):
        """
        Suspend an account holder
        """
        endpoint = f"/suspendAccountHolder"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def un_suspend_account_holder(self, request, idempotency_key=None, **kwargs):
        """
        Unsuspend an account holder
        """
        endpoint = f"/unSuspendAccountHolder"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def update_account_holder(self, request, idempotency_key=None, **kwargs):
        """
        Update an account holder
        """
        endpoint = f"/updateAccountHolder"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def update_account_holder_state(self, request, idempotency_key=None, **kwargs):
        """
        Update payout or processing state
        """
        endpoint = f"/updateAccountHolderState"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

