from ..base import AdyenServiceBase


class AccountsApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super(AccountsApi, self).__init__(client=client)
        self.service = "platformsAccount"

    def close_account(self, request, idempotency_key=None, **kwargs):
        """
        Close an account
        """
        endpoint = f"/closeAccount"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def create_account(self, request, idempotency_key=None, **kwargs):
        """
        Create an account
        """
        endpoint = f"/createAccount"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def update_account(self, request, idempotency_key=None, **kwargs):
        """
        Update an account
        """
        endpoint = f"/updateAccount"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

