from ..base import AdyenServiceBase


class VerificationApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super(VerificationApi, self).__init__(client=client)
        self.service = "platformsAccount"

    def check_account_holder(self, request, idempotency_key=None, **kwargs):
        """
        Trigger verification
        """
        endpoint = f"/checkAccountHolder"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def delete_bank_accounts(self, request, idempotency_key=None, **kwargs):
        """
        Delete bank accounts
        """
        endpoint = f"/deleteBankAccounts"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def delete_legal_arrangements(self, request, idempotency_key=None, **kwargs):
        """
        Delete legal arrangements
        """
        endpoint = f"/deleteLegalArrangements"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def delete_payout_methods(self, request, idempotency_key=None, **kwargs):
        """
        Delete payout methods
        """
        endpoint = f"/deletePayoutMethods"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def delete_shareholders(self, request, idempotency_key=None, **kwargs):
        """
        Delete shareholders
        """
        endpoint = f"/deleteShareholders"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def delete_signatories(self, request, idempotency_key=None, **kwargs):
        """
        Delete signatories
        """
        endpoint = f"/deleteSignatories"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def get_uploaded_documents(self, request, idempotency_key=None, **kwargs):
        """
        Get documents
        """
        endpoint = f"/getUploadedDocuments"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def upload_document(self, request, idempotency_key=None, **kwargs):
        """
        Upload a document
        """
        endpoint = f"/uploadDocument"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

