# Those constants are used from the library only
BASE_TERMINAL_URL = "https://postfmapi-{}.adyen.com/postfmapi/terminal"
BASE_MANAGEMENT_URL = "https://management-{}.adyen.com"
BASE_LEGAL_ENTITY_MANAGEMENT_URL = "https://kyc-{}.adyen.com/lem"
PAL_LIVE_ENDPOINT_URL_TEMPLATE = "https://{live_prefix}-pal-live" \
                                 ".adyenpayments.com/pal/servlet"
PAL_TEST_URL = "https://pal-test.adyen.com/pal/servlet"
ENDPOINT_CHECKOUT_TEST = "https://checkout-test.adyen.com"
ENDPOINT_CHECKOUT_LIVE_SUFFIX = "https://{live_prefix}-checkout-live" \
                                ".adyenpayments.com/checkout"
API_BIN_LOOKUP_VERSION = "v52"
API_CHECKOUT_VERSION = "v69"
API_CHECKOUT_UTILITY_VERSION = "v1"
API_MANAGEMENT_VERSION = "v1"
API_RECURRING_VERSION = "v68"
API_PAYMENT_VERSION = "v64"
API_PAYOUT_VERSION = "v68"
API_TERMINAL_VERSION = "v1"
API_LEGAL_ENTITY_MANAGEMENT_VERSION = "v2"
LIB_VERSION = "7.1.1"
LIB_NAME = "adyen-python-api-library"
