from ..base import AdyenServiceBase


class DocumentsApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super().__init__(client=client)
        self.service = "documentCollector"
        self.baseUrl = "https://document-collector-test.adyen.com/v1"

    def upload_cross_border_invoice(self, idempotency_key=None, **kwargs):
        """
        Upload a document
        """
        endpoint = self.baseUrl + "/crossBorderInvoices"
        method = "POST"
        return self.client.call_adyen_api(
            None, self.service, method, endpoint, idempotency_key, **kwargs
        )
