from ..base import AdyenServiceBase


class ModificationsApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super(ModificationsApi, self).__init__(client=client)
        self.service = "payments"

    def change_the_authorised_amount(self, request, idempotency_key=None, **kwargs):
        """
        Change the authorised amount
        """
        endpoint = f"/adjustAuthorisation"
        endpoint = endpoint.replace('/', '', 1)
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def cancel_authorisation(self, request, idempotency_key=None, **kwargs):
        """
        Cancel an authorisation
        """
        endpoint = f"/cancel"
        endpoint = endpoint.replace('/', '', 1)
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def cancel_or_refund_payment(self, request, idempotency_key=None, **kwargs):
        """
        Cancel or refund a payment
        """
        endpoint = f"/cancelOrRefund"
        endpoint = endpoint.replace('/', '', 1)
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def capture_authorisation(self, request, idempotency_key=None, **kwargs):
        """
        Capture an authorisation
        """
        endpoint = f"/capture"
        endpoint = endpoint.replace('/', '', 1)
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def create_donation(self, request, idempotency_key=None, **kwargs):
        """
        Create a donation
        """
        endpoint = f"/donate"
        endpoint = endpoint.replace('/', '', 1)
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def refund_captured_payment(self, request, idempotency_key=None, **kwargs):
        """
        Refund a captured payment
        """
        endpoint = f"/refund"
        endpoint = endpoint.replace('/', '', 1)
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def cancel_authorisation_using_your_reference(self, request, idempotency_key=None, **kwargs):
        """
        Cancel an authorisation using your reference
        """
        endpoint = f"/technicalCancel"
        endpoint = endpoint.replace('/', '', 1)
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

    def cancel_inperson_refund(self, request, idempotency_key=None, **kwargs):
        """
        Cancel an in-person refund
        """
        endpoint = f"/voidPendingRefund"
        endpoint = endpoint.replace('/', '', 1)
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

