templateDir: ./templates
files:
  api-single.mustache:
    folder: api
    destinationFilename: api-single.py
    templateType: SupportingFiles
  api-small.mustache:
    destinationFilename: -small.py
    templateType: API
  service_readme.mustache:
    templateType: APIDocs
    destinationFilename: Overview.md