from ..base import AdyenServiceBase
from .disputes_api import DisputesApi


class AdyenDisputesApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super(AdyenDisputesApi, self).__init__(client=client)
        self.disputes_api = DisputesApi(client=client)
