from ..base import AdyenServiceBase


class TransfersApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super(TransfersApi, self).__init__(client=client)
        self.service = "transfers"

    def transfer_funds(self, request, idempotency_key=None, **kwargs):
        """
        Transfer funds
        """
        endpoint = f"/transfers"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

