name: "Run tests"
on:
  pull_request:
    branches:
      - automation/services


jobs:
  tests:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-20.04
#    strategy:
#      matrix:
#        python-version: [ '3.6','3.7', '3.8' ]
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
        sudo apt-get update
        sudo apt install libcurl4-openssl-dev
    - name: Test with tox
      run: tox

    - name: Add label if tests fail
      uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d # v6
      if: ${{ failure() }}