name: Publish Python

on:
  release:
    types: [published]

permissions:
  contents: read
  
jobs:
  tests:
    name: run tests
    uses: ./.github/workflows/python-ci.yml
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    needs: [tests]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      
      - name: Install UV
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: "3.14"

      - name: Build a binary wheel and a source tarball
        run: uv build

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          password: ${{ secrets.PYPI_KEY }}
