from ..base import AdyenServiceBase


class SessionAuthenticationApi(AdyenServiceBase):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, client=None):
        super(SessionAuthenticationApi, self).__init__(client=client)
        self.service = "sessionAuthentication"
        self.baseUrl = "https://test.adyen.com/authe/api/v1"

    def create_authentication_session(self, request, authenticationSessionRequest, idempotency_key=None, **kwargs):
        """
        Create a session token
        """
        endpoint = self.baseUrl + f"/sessions"
        method = "POST"
        return self.client.call_adyen_api(request, self.service, method, endpoint, idempotency_key, **kwargs)

